apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firstrs
  labels:
    app: rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
        - name: nginx
          image: nginx:latest
# any update will not be reflected to the running pods, new ones will be created as per the new spec.
